// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:cdf315b9-b484-4596-865e-7890c1f84be9",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_gFuS4bWFO",
  aws_user_pools_web_client_id: "c8p9c7uo3r5ho4v1o49ej9dje",
  oauth: {}
};

export default awsmobile;
